version: '3.8'

services:
  telegram-bot:
    build: .
    container_name: telegram_bot
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - OWNER_ID=${OWNER_ID}
    volumes:
      - ./media:/media
    ports:
      - "8443:8443"
